# -*- coding: utf-8 -*-
"""2.vowel or consonant

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SduP87SrvYDQulTvbaIqNTqBpOtZ_CTB
"""

letter = input("Enter a single character: ")
if len(letter) != 1 or not letter.isalpha():
    print("Please enter a valid single letter.")
elif letter in "aeiou":
      print(f"{letter} is a vowel.")
else:
      print(f"{letter} is a consonant.")