# -*- coding: utf-8 -*-
"""3.temperature converter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16FdEp30efUeFns7OzzCukMTuArGvd5Cu
"""

temp = float(input("Enter temperature: "))
choice = input("Convert to (F)ahrenheit or (C)elsius?")
if choice == "f":
  converted = (temp * 9/5) + 32
  print(f"{temp} Celsius is {converted} Fahrenheit.")
elif choice == "c":
  converted = (temp - 32) * 5/9
  print(f"{temp} Fahrenheit is {converted} Celsius.")
else:
  print("Invalid choice.")